### ISSUE TITLE
Output SAUCE Metadata as PNG tEXt Chunks

### ISSUE THREAD

**Issue by christianvozar** [ansilove/ansilove#17]
A bit of a thought experiment in discussing the output of ansi to PNG with the maintainer of 16c, James Bodie.

I had the thought to create a function that would take SAUCE metadata and write it (optionally perhaps) to the PNG as tEXt chunks such that when viewing the PNG with something like macOS Preview -> Tools -> Show Inspector it would show the SAUCE data converted to PNG metadata.

I was able to edit the PNG in Adobe Lightroom and test it manually to see what would show yielding:
![screen shot 2017-12-19 at 3 24 46 pm](https://user-images.githubusercontent.com/419688/34181815-fc61793e-e4d0-11e7-998b-ecfa194370b6.png)

The issue I see is that I can't seem to find any documentation in `libgd` for writing tEXt chunks in a PNG. I see how to do it in `libpng` but not in gd. @fcambus any thoughts?

**Comment by ByteProject** [comment]
The question was addressed to @fcambus but I'm sure he doesn't mind if I'm taking over answering and adding my thoughts on this, even a (probably) philosophical point of view. This will be a longer text, be warned.

> I had the thought to create a function that would take SAUCE metadata

Reading, writing and manipulating SAUCE records is already **fully** implemented for `AnsiLove/C` (but just parts are merged to the codebase). The code is based on `libSauce` by @bricas. It is the same code that powers the `ALSauceMachine` class in `AnsiLove.framework`. All I did in the framework was creating a Cocoa layer on top of the already existing SAUCE code in `AnsiLove/C`. Much of `AnsiLove/C`s SAUCE code though sleeps here on my harddrive. I always wanted to add an interface to call these functions from the command line, which is one of the first thoughts I had back when I started `AnsiLove/C` as a fork to `AnsiLove/PHP` (the latter being the original but now deprecated project by @fcambus that started it all). To summarize: the code for making `AnsiLove/C` a full featured SAUCE tool is already existing. I just added this to my todo list as I started it all back in the early stages of the project but never finished the implementation. It's one thing I want `AnsiLove/C` to be capable of. The code that AnsiLove/C currently misses is already implemented in `ALSauceMachine` btw.

What we are actually doing with the code already is showing the SAUCE record either when generating a file, or by just investigating a SAUCE record with the `-s` flag.

![Console call ansilove -s](https://d3vv6lp55qjaqc.cloudfront.net/items/16470l1f1r081L150C3q/Screenshot%20from%202017-12-21%2013-18-46.png)

> and write it (optionally perhaps) to the PNG as tEXt chunks such that when viewing the PNG with something like macOS Preview -> Tools -> Show Inspector it would show the SAUCE data converted to PNG metadata

I'm not sure if I'm with you in this. The idea is quite cool and I like it, though I don't see the actual benefit. When viewing files on your operating system, the way should be to view them with a dedicated viewer like [Ascension](https://github.com/ansilove/Ascension) which is capable of easily displaying the SAUCE record with one click. Another problem is that SAUCE and [PNG metadata](http://dev.exiv2.org/projects/exiv2/wiki/The_Metadata_in_PNG_files) might be too different. When you take a look at the SAUCE record displayed in the console screenshot above, you will notice that it comes with quite an extensive comment, which is 4 lines (in the SAUCE record). It's one of my test files which is available here http://cl.8-bit.info/1O3n3k3u0n3U I think the problem will be that we're not able to transfer all of the SAUCE data in such a transition to the PNG file. And if we can't do that we shouldn't implement the a feature. Regardless whether it's possible or not, I think writing `SAUCE records > PNG exiv` shouldn't be part of the AnsiLove/C codebase. It could be part of a framework on top of the codebase like `AnsiLove.framework` or part of an app that has a `export to PNG` feature like [Ascension](https://github.com/ansilove/Ascension)  (it could be a checkbox in the export save dialog)  but I really don't see the relevance at this point for the option at all.  `¯\_(ツ)_/¯`

> The issue I see is that I can't seem to find any documentation in libgd for writing tEXt chunks in a PNG. I see how to do it in libpng but not in gd. 

Yes I can answer this. `libgd` simply doesn't offer this feature. The GD graphics library is meant for quickly drawing and manipulating image data optimized for the web, where such an option is not necessary. In addition, libgd in fact uses `libpng` for its `gdImagePng` method, which is the method we use in `AnsiLove/C` for generating the PNG output file. Your initial thought was right, `libpng` definitely would be the library to implement the exiv data writing method. Note that this would cause AnsiLove/C to rely on one more dependency (currently GD is the only dependency), which is another reason why I'm against such an implementation. 

Please share your thoughts on this, @fcambus and @christianvozar. I also assigned the issue to myself because I want `AnsiLove/C`being capable of reading, writing and manipulating SAUCE records in the future. It's not much work (since the code is already existing) but handy having a command line utility that can do this. I will take care of the implementation.

**Comment by ByteProject** [comment]
Just a short update on SAUCE editing capabilities: after two nights and some thoughts on the matter I came to the conclusion that SAUCE editing shouldn't be part of AnsiLove/C. What AnsiLove does with SAUCE is already what should be done. I will create a separate (yet unnamed) command line SAUCE editor which will be published here via the AnsiLove organization. Merry Christmas! :)

**Comment by fcambus** [comment]
@ByteProject: no, I don't mind.

And I also agree with your position that while it's a fun idea, Ansilove/C is not the place for such a functionality, the same way SAUCE editor functionalities should be left out as well.

I think that @ByteProject  also agree that at this point, Ansilove/C is pretty much done in term of features, and that the effort should be on cleaning up and simplifying the code and getting rid of stuff inherited from the PHP version.

During the Christmas holiday, I was finally able to tackle something we had been discussing for quite a while, which is splitting the project into a shared library and a CLI tool. The library is up at [libansilove](https://github.com/ansilove/libansilove/) and there is also a [libansilove](https://github.com/ansilove/ansilove/tree/libansilove) branch in this repository which makes use of the library.

**Comment by fcambus** [comment]
@christianvozar I'm glad you opened this issue though, because one thing on my TODO list was to evaluate the possibility of dropping GD altogether (which was inherited from the PHP version) and use plain libpng instead. Do you have any experience with libpng? Does it sounds realistic?

**Comment by christianvozar** [comment]
Heya guys, I've been deep at work and life and haven't had a chance to reply. Sorry for the delay.

@fcambus on libpng. My experience with libpng is only when I had to modify png files to include data such as EXIF data that I couldn't do otherwise. I'm not sure what benefits we would get moving from gd, maybe some minor performance in rendering?

@ByteProject You have convinced me to your way of thinking about this. You are right, the functionality I put forth doesn't belong in `ansilove/c`, it really would be part of some app higher up the rendering stack. Originally my thought was "Well we are rendering an art format that most machines can't view unless in a standard image format like PNG, so why not include the metadata in the PNG format so you get a fully ported file..." which made sense initially but the more I have thought on it there really isn't a time you view a PNG of ansi art without some specialized viewer which would also be handling how SAUCE is displayed. So I retract my proposal.

I'm happy to see that the primary library will have full sauce editing capabilities. Very cool.
