### ISSUE TITLE
Render Failure for .ANS

### ISSUE THREAD

**Issue by Sembiance** [ansilove/ansilove#34]
Greetings. ansilove is AWESOME!

However it fails to properly render this ANS file: https://16colo.rs/pack/blocktronics_yotb/WZ%20-%20Portrait%20Blonde.ans
Source: https://16colo.rs/pack/blocktronics_yotb/raw/WZ%20-%20Portrait%20Blonde.ans

deark seems to handle it ok.

**Comment by bart-d** [comment]
I'm not really sure where exactly this ANSI wouldn't have been rendered properly, could you please elaborate on where you are seeing issues?

not familiar with 'deark', what is it?

**Comment by Sembiance** [comment]
deark is a program that handles conversions of lots of files. This includes converting old ANSI art files into PNG. You can get it here:
https://github.com/jsummers/deark
https://entropymine.com/deark/

Running deark on the command line as `deark -opt char:output=image "WZ - Portrait Blonde.ans"` produces this png:
![deark](https://user-images.githubusercontent.com/81436/90349096-6b216e00-e006-11ea-9ba4-7a158efb82fa.png)

Running ansilove on the command line as `ansilove "WZ - Portrait Blonde.ans"` produces this png:
![ansilove](https://user-images.githubusercontent.com/81436/90349095-6b216e00-e006-11ea-8f52-e7bf785399e6.png)

**Comment by bart-d** [comment]
What you see on 16colo.rs is rendered with ansilove. You just need to supply the proper width with the -w parameter, (in this case 220). ansilove -i -c 220 "WZ - Portrait Blonde.ans" will render this file correctly.

deark seems to rely on SAUCE and thus retrieves the width automatically (if present). afaik ansilove only reads the ice colors flag from SAUCE.

**Comment by Sembiance** [comment]
Ahh, so this is user error on my part.

It would be a nice improvement for ansilove to determine width automatically from the SAUCE when it isn't explicitly provided via a  user parameter, but that's probably a separate issue.

Thanks for the info!

**Comment by bricas** [comment]
WRT the SAUCE image width specification, I would add that the accuracy of that info is highly suspect for older files. I'm not sure if it was bad tools, corrupt files or what, but I found myself on several occasions having to discard that info. It's great when it works though!

**Comment by bart-d** [comment]
by default 16colo.rs parses SAUCE and adds parameters to ansilove accordingly. there are indeed files that have a wrong SAUCE settings out there, but it's only a handful compared to those which have a correct width, flags or fonts settings. as i see it, the error margin is more than acceptable. as you can see in the example above, it works both ways, especially artworks created in recent years always have SAUCE and a width correctly set because the editor does it automatically, those don't convert properly by default.

i've suggested in the past to add a new parameter for ansilove to follow SAUCE specs, which wouldn't change the standard behavior but at least allow to user to decide for himself to follow SAUCE or not.

**Comment by bricas** [comment]
Agreed -- I think that would be an excellent feature!

**Comment by bricas** [comment]
@bart-d I've submitted #35 -- please add any additional info, use cases, etc, you can think of. Cheers.

**Comment by bart-d** [comment]
FYI, new -S flag in 4.1.3 will use SAUCE for rendering hints

**Comment by Sembiance** [comment]
Awesome news about the new flag! Thanks!
